import Link from 'next/link';
import SiteChrome,{Arrow} from '../../components/SiteChrome';
import StockPhoto from '../../components/StockPhoto';
import BrandLogo from '../../components/BrandLogo';
import {stock,premiumStock as p} from '../../lib/stockImages';
export default function About(){return <SiteChrome><main className="inner-page about-page">
  <section className="about-hero"><StockPhoto src={p.studio} className="about-hero-photo"/><div className="about-hero-shade"/><div className="about-hero-copy"><p className="eyebrow">SRI RAJAN PHOTOGRAPHY</p><h1>We photograph<br/><em>what time changes.</em></h1></div></section>
  <section className="about-manifesto"><div><p className="eyebrow">OUR STUDIO</p><BrandLogo/></div><div><h2>Photography becomes valuable when the moment is gone.</h2><p>That idea guides everything we create. We photograph celebrations, families and milestones with a balance of observation and direction — giving real emotion enough space while bringing a refined visual point of view to every frame.</p><p>Our studio brings photography, cinematic films, album design and finished wall pieces together so the story does not stop at a folder of digital files.</p></div></section>
  <section className="about-editorial"><StockPhoto src={p.photographer} className="about-editorial-photo"/><div><p className="eyebrow">HOW WE SEE</p><h2>Light. People. Timing. Everything else comes second.</h2><p>We look for photographs that can survive trends: genuine expressions, strong composition, beautiful light and details that reveal where the story happened.</p><Link href="/portfolio" className="text-link dark-link">Explore our portfolio <Arrow/></Link></div></section>
  <section className="about-values section-dark"><p className="eyebrow">WHAT MATTERS TO US</p><div className="about-values-grid">{[['01','Emotion over performance','The experience should never become less important than the photograph.'],['02','Consistency over trends','Your gallery should feel coherent today and still feel elegant years from now.'],['03','Objects that last','Albums and prints turn digital memories into things families can actually inherit.']].map(v=><article key={v[0]}><span>{v[0]}</span><h3>{v[1]}</h3><p>{v[2]}</p></article>)}</div></section>
  <section className="about-cta"><StockPhoto src={stock.album} className="about-cta-photo"/><div><p className="eyebrow">WORK WITH US</p><h2>Tell us what<br/><em>you want to remember.</em></h2><Link href="/contact" className="button button--light">Start an enquiry <Arrow/></Link></div></section>
</main></SiteChrome>}
